$(document).ready(function(){
	var i=0;
	if(i==0){
	$("#b1").prop("disabled",true);
	$("#b1").css("opacity",0.8);
	}
	$("div").text(i);
	$("#b1").click(function(){
	i--;
	if(i<10){
	$("#b3").prop("disabled",false);
	$("#b3").css("opacity",1);
	}
	if(i==0){
	$(this).prop("disabled",true);
	$(this).css("opacity",0.8);
	}
	$("div").text(i);
	if(i%2==0){
	$("body").css("background-color","blue");
	$("div").css("color","white");
	}
	if(i%2!=0){
	$("body").css("background-color","grey");
	$("div").css("color","red");
	}
	});
	$("#b3").click(function(){
	i++;
	if(i>0){
	$("#b1").prop("disabled",false);
	$("#b1").css("opacity",1);
	}
	if(i==10){
	$(this).prop("disabled",true);
	$(this).css("opacity",0.8);
	}
	$("div").text(i);
	if(i%2==0){
	$("body").css("background-color","blue");
	$("div").css("color","white");
	}
	if(i%2!=0){
	$("body").css("background-color","grey");
	$("div").css("color","red");
	}
	});
	$("#b2").click(function(){
	i=0;
	$("#b3").prop("disabled",false);
	$("#b3").css("opacity",1);
	$("#b1").prop("disabled",true);
	$("#b1").css("opacity",0.8);
	$("div").text("0");
	if(i%2==0){
	$("body").css("background-color","blue");
	$("div").css("color","white");
	}
	if(i%2!=0){
	$("body").css("background-color","grey");
	$("div").css("color","red");
	}
	});
});